config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "kittens#index"
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
  validates :age, numericality: { greater_than_or_equal_to: 1 }
  validates :cuteness, numericality: { greater_than_or_equal_to: 1,
    less_than_or_equal_to: 10 }
  validates :softness, numericality: { greater_than_or_equal_to: 1,
    less_than_or_equal_to: 10 }

  # def softness_cuteness_overload
  #   if softness > 10
  #     errors.add(:softness, "Kitty is too soft!!")
  #   end
  #   if cuteness > 10
  #     errors.add(:cuteness, "Kitty is too cute!!")
  #   end
  # end

  # def softness_cuteness_underload
  #   if softness < 0
  #     errors.add(:softness, "Kitty cannot be rock-like.")
  #   end
  #   if cuteness < 0
  #     errors.add(:cuteness, "IMPOSSIBLE!!!")
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])


    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitty_params)

    if @kitten.save
      flash[:notice] = "Welcome to the world, #{@kitten.name}!"
      redirect_to @kitten
    else
      flash[:notice] = "Silly human..."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitty_params)
      redirect_to @kitten
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    flash[:notice] = "You... you heartless monster!"
    redirect_to kittens_path
  end

  private

  def kitty_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten_form.html.erb
<%= form_with model: @kitten do |f| %>
  <% if flash[:notice] %>
    <%= flash[:notice] %> <br>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :age %>
  <%= f.number_field :age, min: 1 %>
  <br>

  <%= f.label :cuteness %>
  <%= f.number_field :cuteness %>
  <br>

  <%= f.label :softness %>
  <%= f.number_field :softness %>
  <br>

  <%= f.submit %>

<% end %>

app/views/kittens/edit.html.erb
<h1>Edit a Kitten</h1>

<%= render "kitten_form" %>

<%= link_to "Delete Kitten", kitten_path(@kitten), method: :delete %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>
<%= link_to "Create a Kitten!", new_kitten_path %>

<br>

<% if flash[:notice]%>
  <%= flash[:notice] %>
  <br>
<% end %>

<ul>
  <% @kittens.each do |k| %>
    <li><%= link_to k.name, k %></li>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<h1>Create a new Kitten</h1>

<%= render "kitten_form" %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>

<% if flash[:notice]%>
  <%= flash[:notice] %>
  <br>
<% end %>

<div>
  Age: <%= @kitten.age %>
</div>

<br>

<div>
  Cuteness: <%= @kitten.cuteness %>
</div>

<br>

<div>
  Softness: <%= @kitten.softness %>
</div>
<br>

<%= link_to "Edit Kitten", edit_kitten_path %>
<br>
<%= link_to "Delete Kitten", kitten_path(@kitten), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure you want to delete the kitty?"
    } %>
<br>
<%= link_to "Index", kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>